name: serde_annotation
description: "Annotations for the serde_dart library, providing a way to serialize and deserialize data structures."
version: 0.0.1
homepage: https://github.com/geekswamp/serde_dart
repository: https://github.com/geekswamp/serde_dart
issue_tracker: https://github.com/geekswamp/serde_dart/issues
topics: ["serde", "serde-dart", "build-runner", "annotation"]

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
